baseURL = "https://chinrui.github.io/"
languageCode = "en-us"
theme = "rui chen"

[params]
    title = "Rui CHEN's HOMEPAGE"
    author = "Rui CHEN"
    description = "Website title"
    copyright = "Rui CHEN"

    [params.theme]
        allowToggle = true
        mainTheme = "light"
        altTheme = "dark"

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Rui CHEN"
        tagline = "Graduate Student"
        location = "Kyoto University, Japan"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

              
        
        
        

        [[params.social.list]]
            class = "far"
            icon = "fa-envelope"
            url = "mailto: chinrui_333@hotmail.com"
            title = "Email_address"

        
        

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "publication" 
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"

        description_1 = """I studied Computer Science related subjects like <font color=brown>rogramming, algorithm, and machine learning</font> for about 7 years. I am very familiar with <font color=brown>R, Python, sklearn and Keras.</font>""" 

        description_2="""I am mostly interested in: \n"""
        description_5 = "<font color=cc6699>Data Science</font>"
        description_6 = "<font color=cc6699>Machine Learning</font>"
        description_7 = "<font color=cc6699>Social and Information Network Analysis</font>"
        description_8 = "<font color=cc6699>Computational Social Science</font>"
        

        

        description_3="""My **current research** is about game theory to optimize the prediction model based on the incentive system for agents, which has high relative with human-computer interaction. I use different kinds of incentive mechanism, which starting from the area in <font color=brown>social networking and market economics</font> to reward agents to choose high-quality factors and induce collective intelligence for the high prediction accuracy. For example, it can be applied to economic market or the prediction of presidential selection.\n """ 

        

        description_4="""I am excited that I could use my knowledge from computer science to a bigger world. Meanwhile, I am also considering about how could the research contribute to the society."""






    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "**Academic Exchange in EPFL**"
            college = "École Polytechnique Fédérale de Lausanne (EPFL)"
            url="https://www.epfl.ch/schools/ic/"
            dates = "**Sep. 2019 - Feb. 2020**"
            
        [[params.education.list]]
            degree = "**M.S. in Computer Science**"
            college = "Kyoto University"
            dates = "**Apr. 2018 - Mar. 2020**"
            url="http://www.soc.i.kyoto-u.ac.jp/en/"
            thesis_title = "**Ishida and Matsubara Laboratory**"
            thesis_link = "http://www.ai.soc.i.kyoto-u.ac.jp/en/"

        [[params.education.list]]
            degree = "**Research Student in Academic Center for Computing and Media Studies**"
            college = "Kyoto University"
            dates = "**Apr. 2017 - Mar. 2018**"
            url="http://www.media.kyoto-u.ac.jp/accms_web/en/"
            thesis_title = "**Visualization Laboratory**"
            thesis_link = "http://www.viz.media.kyoto-u.ac.jp/html/en/index.html"

        [[params.education.list]]
            degree = "**B.S. in Information and Communication Enginnering**"
            college = "University Of Electronic Science And Technology Of China (UESTC)"
            url="https://en.uestc.edu.cn/"
            dates = "**Sep. 2012 - Jun. 2016**"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Improving the accuracy of collective prediction by maintaining the diversity of opinions"
            
            description1 = """**<font color=cc9999>Background:</font>** Decisions made by a single individual tend to be inaccurate compared to decisionsmade by majority. Collective intelligence is a process of sharing or group intelligence, and assembling opinions from others into decision-making \n """

            description2 = """**<font color=cc9999>Add Incentive:</font>** Based on previous research to give incentive for agents and induce collective intelligence, in order to improve the prediction accuracy."""

            description3 = """**<font color=cc9999>Evaluation:</font>** Different incentives can be used to dynamically improve the prediction accuracy with different number of agents participate in."""


        [[params.project.list]]
            title = "Data-based traffic route planning in Japan"
            
            description1 = """**<font color=cc9999>Data Processing:</font>** Collect and process data to obtain correlations between on geographic information data and commuting time among Japanese cities."""

            description2 = """**<font color=cc9999>Data Analysis and Visualization:</font>** Analyze the traffic connections between cities (i.e. the means of transportation used, the time, the number of nodes passing through) to obtain the geographic transportation network graph between cities in Japan."""

            description3 = """**<font color=cc9999>Traffic Optimization:</font>** Find hot spot cities through data visualization,and let them as radiation centers to add faster or new traffic routes, in order to reduce the commuting time of public equipment between cities."""


        [[params.project.list]]
            title = "Database-based web application development"
            
            description1 = """Used Ruby on Rails to develop database-based web application BBS."""

            description2 = """Finished basic functions, such as, registration, post data statistics and several database operations."""


    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "paper_name", "journal"]

        [[params.publication.list]]
            paper_name = "Improving the Accuracy of the Collective Prediction by Maintaining the Diversity of Opinions: Preliminary Report"
            authors = "Rui Chen, Shigeo Matsubara"
            date = "2019"
            journal = "Annual Conference of Japanese Society and Artificual Intelligence (JSAI)"

                   

    # Skill section
    [params.skill]
        title = "Skills and Interests"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Motivation in Research"
            skillrating = 99
        [[params.skill.list]]
            skill = "Programing Languages: Python, R, Matlab etc."
            skillrating = 85
        [[params.skill.list]]
            skill = "Average (English, Mandarin, Japanese)"
            skillrating = 80
        [[params.skill.list]]
            skill = "Basic Knowledge in Mathematics & Algorithms"
            skillrating = 85

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
        
        [[params.hobby.list]]       
            hobby = "Cooking Sichuan cuisines & Enjoy delicious food with friends"
        [[params.hobby.list]]       
            hobby = "Data Analysis Competition"
        [[params.hobby.list]]       
            hobby = "Also Like doing research on Joke-Telling & Anime"